
import type { Metadata } from "next";
import { ABeeZee, Geist, Geist_Mono ,ADLaM_Display} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
const inter=ABeeZee({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "400",
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
      >
         <div className="flex flex-col gap-4 ">
              <Header />
              <div className='flex flex-col w-full'>
                {children}
              </div>
            </div>
      </body>
    </html>
  );
}
